  <?php require_once('overall_header.phtml'); ?>

    <div id="app">
      <div class="section">
          <div class="container">
              <div class="row">
                  <div class="title-area">
                      <h2><?php echo $dates["labels"]["label_1"]["title"]; ?></h2>
                      <div class="separator separator-danger">X</div>
                  </div>
              </div>
              <div class="row">
                <?php foreach ($dates["labels"]["label_1"]["content"] as $key => $value) { ?>
                  <div class="col-md-4">
                      <div class="info-icon">
                          <div class="icon text-danger">
                              <i class="pe-7s-graph1"></i>
                          </div>
                          <h3><?php echo $value["title"]; ?></h3>
                          <p class="description"><?php echo $value["description"]; ?></p>
                      </div>
                  </div>
                <?php } ?>
              </div>
          </div>
      </div>

      <div class="section section-our-team-freebie">
          <div class="parallax filter filter-color-black">
              <div class="image" style="background-image:url('http://hdwallsize.com/wp-content/uploads/2013/05/Cars-Game-Gran-Turismo-6-Wallpaper-HD.jpeg')">
              </div>
              <div class="container">
                  <div class="content">
                      <div class="row">
                          <div class="title-area">
                              <h2><?php echo $dates["labels"]["label_2"]["title"]; ?></h2>
                              <div class="separator separator-danger">X</div>
                              <p class="description"><?php echo $dates["labels"]["label_2"]["description"]; ?></p>
                          </div>
                      </div>

                      <div class="team">
                          <div class="row">
                              <div class="col-md-10 col-md-offset-1">

                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                                  <!-- Wrapper for slides -->
                                  <div class="carousel-inner" role="listbox">
                                    <?php $i = 0; ?>
                                    <?php foreach ($dates["labels"]["label_2"]["content"] as $key => $value) { ?>
                                      <?php ($i == 0) ? $class = "active" : $class = ""; ?>
                                      <div class="item <?php echo $class; ?>">

                                        <div class="row">
                                            <?php for ($x=0; $x < count($value["pilotos"]); $x++) { ?>
                                              <div class="col-md-4">
                                                  <div class="card card-member">
                                                      <div class="content">
                                                          <div class="avatar avatar-danger">
                                                              <img alt="..." class="img-circle" src="view/assets/img/faces/face_1.jpg"/>
                                                          </div>
                                                          <div class="description">
                                                              <h3 class="title"><?php echo $value["pilotos"][$x]; ?></h3>
                                                              <p class="small-text">Uriracing / GT5</p>
                                                              <p class="description">I miss the old Kanye I gotta say at that time I’d like to meet Kanye And I promise the power is in the people and I will use the power given by the people to bring everything I have back to the people.</p>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                            <?php } ?>

                                        </div>
                                        <?php $i++; ?>

                                      </div>
                                    <?php }?>

                                  </div>

                                </div>

                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <!-- Races -->
      <div class="section">
          <div class="container">
              <div class="row">
                <?php echo $dates["services"]; ?>
              </div>
              <div class="row">
                  <div class="col-md-4">
                      <div class="info-icon">
                          <div class="icon text-danger">
                              <i class="pe-7s-graph1"></i>
                          </div>
                          <h3>Sales</h3>
                          <p class="description">We make our design perfect for you. Our adjustment turn our clothes into your clothes.</p>
                      </div>
                  </div>
                  <div class="col-md-4">
                      <div class="info-icon">
                          <div class="icon text-danger">
                              <i class="pe-7s-note2"></i>
                          </div>
                          <h3>Content</h3>
                          <p class="description">We create a persona regarding the multiple wardrobe accessories that we provide..</p>
                      </div>
                  </div>
                  <div class="col-md-4">
                      <div class="info-icon">
                          <div class="icon text-danger">
                              <i class="pe-7s-music"></i>
                          </div>
                          <h3>Music</h3>
                          <p class="description">We like to present the world with our work, so we make sure we spread the word regarding our clothes.</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <div class="section section-small section-get-started">
          <div class="parallax filter">
              <div class="image"
                  style="background-image: url('view/assets/img/office-1.jpeg')">
              </div>
              <div class="container">
                  <div class="title-area">
                      <h2 class="text-white">Do you want to work with us?</h2>
                      <div class="separator line-separator">♦</div>
                      <p class="description"> We are keen on creating a second skin for anyone with a sense of style! We design our clothes having our customers in mind and we never disappoint!</p>
                  </div>

                  <div class="button-get-started">
                    <div class="contact-form">
                      <form method="post">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Email address</label>
                          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                        </div>
                        <div class="form-group">
                          <label for="exampleInputPassword1">Password</label>
                          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                        <div class="form-group">
                          <a href="#gaia" class="btn btn-danger btn-fill btn-lg">Contact Us</a>
                        </div>
                      </form>
                    </div>
                  </div>
              </div>
          </div>
      </div>

    </div>
    <!--/ app -->


  <?php require_once('overall_footer.phtml'); ?>
