<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8" />
      <link rel="apple-touch-icon" sizes="76x76" href="view/assets/img/apple-icon.png">
      <link rel="icon" type="image/png" sizes="96x96" href="view/assets/img/favicon.png">

      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
      <title>Gaia - Bootstrap Template | Free Demo</title>
      <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
      <link href="view/assets/css/bootstrap.css" rel="stylesheet" />
      <link href="view/assets/css/gaia.css" rel="stylesheet"/>

      <!--     Fonts and icons     -->
      <link href='https://fonts.googleapis.com/css?family=Cambo|Poppins:400,600' rel='stylesheet' type='text/css'>
      <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
      <link href="view/assets/css/fonts/pe-icon-7-stroke.css" rel="stylesheet">

      <style media="screen">
        img.logoj{
          max-width: 100%;
          height: 170px;
        }
        .carousel-control.left{
          background: none;
        }
        .carousel-control.right{
          background: none;
        }
        .card{
          box-shadow: none;
        }
      </style>

  </head>

  <body>

    <nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
        <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
        <div class="container">
            <div class="navbar-header">
                <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <!-- <a href="http://www.creative-tim.com" class="navbar-brand">JIM Racing team</a> -->
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-left navbar-uppercase">
                  <li>
                      <a href="#"><i class="fa fa-facebook-square"></i> Facebook</a>
                  </li>
                  <li>
                      <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
                  </li>
                  <li>
                      <a href="#"><i class="fa fa-instagram"></i> Instagram</a>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right navbar-uppercase">
                    <li>
                        <a href="http://www.creative-tim.com/product/gaia-bootstrap-template-pro" target="_blank">Quiénes somos</a>
                    </li>
                    <li>
                        <a href="http://www.creative-tim.com/product/gaia-bootstrap-template" class="btn btn-success btn-fill">Register</a>
                    </li>
                    <li>
                        <a href="http://www.creative-tim.com/product/gaia-bootstrap-template" class="btn btn-danger btn-fill">Log in</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>

    <div class="section section-header">
        <div class="parallax filter filter-color-red">
            <div class="image"
                style="background-image: url('view/assets/img/audi-backfire-flame-motion-blur-night-r8-race-car.jpg')">
            </div>
            <div class="container">
                <div class="content">
                    <div class="title-area">
                        <img src="view/assets/img/logoj.png" class="logoj" alt="" />
                        <!-- <h1 class="title-modern">Gaia</h1> -->
                        <h3>You'll never drive alone!</h2>
                        <div class="separator line-separator">♦</div>
                    </div>

                    <div class="button-get-started">
                        <a href="http://www.creative-tim.com/product/gaia-bootstrap-template" target="_blank" class="btn btn-white btn-fill btn-lg ">
                            Login
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
